[package]
name = "wallpaper-manager-ipc"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
xdg = "2.5.2"
